// Home
export const HOME_PRODUCTS_REQUEST = 'HOME_PRODUCTS_REQUEST';
export const HOME_PRODUCTS_SUCCESS = 'HOME_PRODUCTS_SUCCESS';
export const HOME_PRODUCTS_FAILURE = 'HOME_PRODUCTS_FAILURE';
export const HOME_PRODUCTS_REFRESHING = 'HOME_PRODUCTS_REFRESHING';

// Product
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';
export const PRODUCT_REFRESHING = 'PRODUCT_REFRESHING';

// Product Variations
export const PRODUCT_INK_COLOR_SELECTED = 'PRODUCT_INK_COLOR_SELECTED';
export const PRODUCT_TEM_COLOR_SELECTED = 'PRODUCT_TEM_COLOR_SELECTED';
export const PRODUCT_CODE_SELECTED = 'PRODUCT_CODE_SELECTED';
export const PRODUCT_PRINTER_SELECTED = 'PRODUCT_PRINTER_SELECTED';
export const PRODUCT_QUANTITY_CHANGED = 'PRODUCT_QUANTITY_CHANGED';

//Fetch Product Variations
export const PRODUCT_VARIATIONS_REQUEST = 'PRODUCT_VARIATIONS_REQUEST';
export const PRODUCT_VARIATIONS_SUCCESS = 'PRODUCT_VARIATIONS_SUCCESS';
export const PRODUCT_VARIATIONS_FAILURE = 'PRODUCT_VARIATIONS_FAILURE';

//Cart Product
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const EMPTY_CART_ITEM = 'EMPTY_CART_ITEM';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const FETCHING_CART_ITEM = 'FETCHING_CART_ITEM';

//Coupon Code
export const COUPON_CODE_FETCHING = 'COUPON_CODE_FETCHING';
export const COUPON_CODE_PENDING = 'COUPON_CODE_PENDING';
export const COUPON_CODE_SUCCESS = 'COUPON_CODE_SUCCESS';
export const COUPON_CODE_ERROR = 'COUPON_CODE_ERROR';
export const COUPON_CODE_VALIDATE = 'COUPON_CODE_VALIDATE';
export const COUPON_CODE_CANCEL = 'COUPON_CODE_CANCEL';

//Order
export const CREATE_NEW_ORDER_PENDING = 'CREATE_NEW_ORDER_PENDING';
export const CREATE_NEW_ORDER_SUCCESS = 'CREATE_NEW_ORDER_SUCCESS';
export const CREATE_NEW_ORDER_ERROR = 'CREATE_NEW_ORDER_ERROR';

//Orders
export const FETCH_ORDERS_PENDING = 'FETCH_ORDERS_PENDING';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_ERRPOR = 'FETCH_ORDERS_ERRPOR';

//Payment order
export const SUCCESS_PAYMENT = 'SUCCESS_PAYMENT';

//Checkout
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const UNFETCH_CUSTOMER = 'UNFETCH_CUSTOMER';
export const LOAD_ALL_CITY = 'LOAD_ALL_CITY';
export const UPDATE_SELECTED_CITY = 'UPDATE_SELECTED_CITY';
export const SAVE_CUSTOMER_INFO = 'SAVE_CUSTOMER_INFO';
export const LOAD_CUSTOMER_INFO = 'LOAD_CUSTOMER_INFO';

//Fetch product variations
export const FETCH_PRODUCT_VARIATION_PENDING = 'FETCH_PRODUCT_VARIATION_PENDING';
export const FETCH_PRODUCT_VARIATION_SUCCESS = 'FETCH_PRODUCT_VARIATION_SUCCESS';
export const FETCH_PRODUCT_VARIATION_ERROR = 'FETCH_PRODUCT_VARIATION_ERROR';

//Product attribute terms
export const PRODUCT_ATTRIBUTE_TERM_REQUEST = 'PRODUCT_ATTRIBUTE_TERM_REQUEST';
export const PRODUCT_ATTRIBUTE_TERM_SUCCESS = 'PRODUCT_ATTRIBUTE_TERM_SUCCESS';
export const PRODUCT_ATTRIBUTE_TERM_ERROR = 'PRODUCT_ATTRIBUTE_TERM_ERROR';

//Navigation constrains
export const NAVIGATE_TO_ORDER = 'NAVIGATE_TO_CART';

//Notifications
export const NOTIFICATION_SET = 'NOTIFICATION_SET';
export const NOTIFICATION_GET = 'NOTIFICATION_GET';
export const NOTIFICATION_FETCHING = 'NOTIFICATION_FETCHING';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_DELETE = 'NOTIFICATION_DELETE';

//Banner slider
export const FETCH_BANNERSLIDER_BEGIN = 'FETCH_BANNERSLIDER_BEGIN';
export const FETCH_BANNERSLIDER_SUCCESS = 'FETCH_BANNERSLIDER_SUCCESS';
export const FETCH_BANNERSLIDER_FAILURE = 'FETCH_BANNERSLIDER_FAILURE';

